unit _146p;

{ P©¡kazy a zpr vy pou‘it‚ v programu TVx. }

interface

const
  {- P©¡kazy pou‘it‚ v nab¡dce programu: }
  cmAbout    = 101;
  cmDate     = 102;
  cmBlueWin  = 103;
  cmCyanWin  = 104;
  cmGrayWin  = 105;
  cmPalette  = 106;
  cmSet      = 107;

  {- Zpr va o uzav©en¡ okna (viz TOkno.Close, TTVApp.HandleEvent): }
  cmCloseWin = 2000;   {*4*}

implementation

end.
