unit _149;

{ Seznam konstant pro n povˆdu v programu TVx. }

interface

const
  {- Konstanty v nab¡dce programu: }
  hcInfo      = 500;
  hcIAbout    = 501;
  hcIDate     = 502;
  hcIQuit     = 503;
  hcWindows   = 504;
  hcNewWindow = 505;
  hcWBlue     = 506;
  hcWCyan     = 507;
  hcWGray     = 508;
  hcWClose    = 509;
  hcWResize   = 510;
  hcWZoom     = 511;
  hcWNext     = 512;
  hcWPrevious = 513;
  hcWTile     = 514;
  hcWCascade  = 515;
  hcConfig    = 516;
  hcCPalette  = 517;
  hcCSet      = 518;

  {- Konstanty v dialogov˜ch oknech: }                   {*5*}
  hcPaletaBarevna = 600;
  hcPaletaCB      = 601;
  hcPaletaMono    = 602;
  hcVstupJmeno    = 603;
  hcVstupFirma    = 604;
  hcVstupAdresa   = 605;
  hcTlacitkoOK    = 606;
  hcTlacitkoZrus  = 607;                                 

implementation

end.
